version: '3.8'

services:
  front-end:
    image: nginx
    volumes:
      - "./front-end:/usr/share/nginx/html:ro"
    ports:
      - "80:80"
    networks:
      - main

  back-end:
    build:
      context: ./back-end
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - main

  timeseries:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=jFc6&>2^i>5>
      - DOCKER_INFLUXDB_INIT_ORG=bats_birds
      - DOCKER_INFLUXDB_INIT_BUCKET=bat_data
    volumes:
      - "influx-data:/var/lib/influxdb"
      - "./timeseries/config:/etc/influxdb2"

  # web:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_USER=root
  #     - DB_PASSWORD=example
  #     - DB_NAME=test_db
  #   volumes:
  #     - .:/usr/src/app
  #   networks:
  #     - mynetwork

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: test_db
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - mynetwork

volumes:
  db-data:
  influx-data:

networks:
  main:
