version: '3.8'

services:
  front-end:
    image: nginx
    volumes:
      - "./front-end:/usr/share/nginx/html:ro"
    ports:
      - "80:80"
    networks:
      - main

  back-end:
    build:
      context: ./back-end
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    volumes:
      - 'grafana_storage:/var/lib/grafana'
      - ./csvuploads:/usr/src/csvuploads

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - main

  timeseries:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=jFc6&>2^i>5>
      - DOCKER_INFLUXDB_INIT_ORG=bats_birds
      - DOCKER_INFLUXDB_INIT_BUCKET=bat_data
    volumes:
      - "influx-data:/var/lib/influxdb"
      - "./timeseries/config:/etc/influxdb2"
    networks:
      - main
    
  telegraf:
    image: telegraf:1.19
    volumes:
      - ./csvuploads:/csvuploads
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
    depends_on:
      - timeseries
    networks:
      - main

volumes:
  grafana_storage:
  db-data:
  influx-data:

networks:
  main:
