{
 "title": "Single sensor view",
 "time": { "from": "2024-09-30T22:00:00.000Z", "to": "2024-10-01T21:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "Sensor",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"bat_data\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"bat_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == ${Sensor:doublequote} and\r\n    (r._field == \"temperature\" or r._field == \"temp1\" or r._field == \"temp2\" or r._field == \"temp3\")\r\n  )"
    }
   ]
  },
  {
   "title": "test table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"bat_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n  |> filter(fn: (r) =>\r\n    r._measurement == ${Sensor:doublequote} and\r\n    (r._field != \"gw\" and r._field != \"sw\")\r\n  )"
    }
   ]
  },
  {
   "title": "luchtvochtigheid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bat_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == ${Sensor:doublequote} and\r\n    (r._field == \"rh\")\r\n  )"
    }
   ]
  }
 ]
}